version: 2
updates:
- package-ecosystem: docker
  directory: /docker
  schedule:
    interval: daily
  commit-message:
    prefix: "[docker] "
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: "[gh-actions] "
