name: build
on:
  workflow_dispatch:
    inputs:
      version:
        description: version, <major>.<minor>.<patch>
        required: true
      url:
        description: URL for UniFi.unix.zip
        required: true
      md5:
        description: MD5 checksum for UniFi.unix.zip
        default: ''
      sha256:
        description: SHA256 checksum for UniFi.unix.zip
        default: ''
run-name: build ${{ inputs.version }}
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Dump inputs
      run: jq .inputs "${GITHUB_EVENT_PATH}"
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Register qemu-user against binfmt_misc
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm,arm64
    - name: Register BuildKit node
      uses: docker/setup-buildx-action@v3
    - name: Login to image registry
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v3
      with:
        username: ${{ vars.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha,scope=build-${{ inputs.version }}
        cache-to: type=gha,scope=build-${{ inputs.version }},mode=max
        context: docker
        platforms: |-
          linux/amd64
          linux/arm64
          linux/arm/v7
        build-args: |-
          URL=${{ inputs.url }}
          MD5=${{ inputs.md5 }}
          SHA256=${{ inputs.sha256 }}
        provenance: false
        outputs: type=image,oci-mediatypes=true
        tags: ${{ vars.IMAGE_PATH }}:${{ inputs.version }}
        push: ${{ github.ref == 'refs/heads/master' }}
